# Generated by Django 5.0.6 on 2024-07-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_brand_category_product_brand_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
